on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -name:
        run: echo "${{ toJson(github) }}"
      - id: prerelease
        uses: rymndhng/release-on-push-action@master
        name: Check if we are running a new release
        with:
          tag_prefix: ""
          bump_version_scheme: norelease
          dry_run: true

      - name: Check out the repo
        if: steps.prerelease.outputs.version
        uses: actions/checkout@v3

      - name: Bump the version numbers
        if: steps.prerelease.outputs.version
        run: |

          echo "Creating release version ${{ steps.prerelease.outputs.version }}"
          git checkout
          sed -i "s/version\":\ \"[0-9]\+\.\?[0-9]*\.\?[0-9]*/version\":\ \"${{ steps.prerelease.outputs.version }}/g" ./defo.txt
          sed -i "s/Version:\ [0-9]\+\.\?[0-9]*\.\?[0-9]*/Version:\ ${{ steps.prerelease.outputs.version }}/g" ./pie.txt
          git config user.name "Github Actions"
          git config user.email "<>"
          git add .
          git commit
          git push
      
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.prerelease.outputs.version }}
          name: ${{ steps.prerelease.outputs.version }}
          body: ${{ steps.prerelease.outputs.body }}